docker/Dockerfile
=> [chore] 스프링부트 Dockerfile 작성

.gitignore, wingle/build.gradle, wingle/src/main/java/kr/co/wingle/HelloController.java, wingle/src/main/java/kr/co/wingle/HelloRequest.java, wingle/src/main/java/kr/co/wingle/HelloResponse.java, wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/common/dto/ApiResponse.java, wingle/src/main/java/kr/co/wingle/common/exception/CustomException.java, wingle/src/main/java/kr/co/wingle/common/exception/RestExceptionHandler.java
ApiResponse를 Base로 사용하시면 됩니다.
코드 보고 피드백 할 사항 있으면 해주세요!
SuccessCode, ErrorCode 만들었고 ExceptionHandler도 만들었습니다.
HelloController에 예시로 example api 만들어두었으니 참고 바랍니다.
예시 포스트맨 테스트입니다.
성공 시 이런 형식으로 응답됩니다.
@RequestBody @Valid 에러는 ExceptionHandler를 통해 처리되며, 이런 형식으로 응답됩니다.
Custom에러는 ErrorCode에 코드 작성 후 CustomException throw 하면 되고, 이런 형식으로 응답됩니다.
resolved: #6
=> [Feature] ApiResponse, Success/ErrorCode, ExceptionHandler 작성

wingle/src/main/java/kr/co/wingle/common/dto/ApiResponse.java, wingle/src/test/java/kr/co/wingle/hello/HelloControllerTest.java
- MockMvc 세팅
- test application.yml에 다음 내용이 추가되어야 합니다. (노션에 전체 코드 있음)
``` YAML
server:
servlet:
encoding:
force-response: true
```
resolved: #11
=> Feat/mock mvc 세팅 #11

wingle/build.gradle, wingle/lombok.config
- JaCoCO 제외 대상 설정하였습니다
+ WingleApplication 클래스
+ hello 패키지
+ common 패키지
+ config 패키지 
+ dto 패키지
+ lombok
resolved: #18
=> [chore] JaCoCo 제외 대상 설정 #18

wingle/build.gradle, wingle/src/main/java/kr/co/wingle/common/config/AmazonS3Config.java, wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/util/S3Util.java
- S3 관련 클래스들 작성했습니다.
- 회원가입 시 학생증 사진은 버킷의 idCardImage 폴더 안에 저장되도록 작성했습니다.
- 하단 커밋 3개만 해당입니다... merge 전이라 다른 브랜치 pull하고 시작했더니 커밋 내역이 섞여서 올라가네요..
resolved: #24
=> [feat] S3 설정

.github/workflows/deploy.yml, wingle/build.gradle, wingle/src/main/java/kr/co/wingle/common/config/RedisConfig.java, wingle/src/main/java/kr/co/wingle/common/config/RestTemplateConfig.java, wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/common/exception/RestExceptionHandler.java, wingle/src/main/java/kr/co/wingle/common/jwt/JwtAuthenticationEntryPoint.java, wingle/src/main/java/kr/co/wingle/common/jwt/JwtFilter.java, wingle/src/main/java/kr/co/wingle/common/jwt/TokenInfo.java, wingle/src/main/java/kr/co/wingle/common/jwt/TokenProvider.java, wingle/src/main/java/kr/co/wingle/common/util/RedisUtil.java, wingle/src/main/java/kr/co/wingle/common/util/SecurityUtil.java, wingle/src/main/java/kr/co/wingle/member/AuthController.java, wingle/src/main/java/kr/co/wingle/member/AuthService.java, wingle/src/main/java/kr/co/wingle/member/CustomUserDetailsService.java, wingle/src/main/java/kr/co/wingle/member/Term.java, wingle/src/main/java/kr/co/wingle/member/TermMember.java, wingle/src/main/java/kr/co/wingle/member/dto/LoginRequestDto.java, wingle/src/main/java/kr/co/wingle/member/dto/MemberResponseDto.java, wingle/src/main/java/kr/co/wingle/member/dto/TokenDto.java, wingle/src/test/java/kr/co/wingle/hello/HelloControllerTest.java, wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java, wingle/src/test/java/kr/co/wingle/member/AuthServiceTest.java, wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
- 테스트코드가 돌아가는 과정에서 오류가 납니다... 로컬에서는 잘 돌아가는데 GitHub actions에서 test failed가 뜹니다. 구글링해보니 mysql 환경이 구축되지 않아서라는데, 이것저것 다 시도해봐도 계속 fail이 뜹니다. 그래서 일단 테스트 제외하고 빌드하는 방식으로 진행하겠습니다. 후에 다시 시도해보곘습니다.
resolved: #34
=> [bug] deploy.yml 빌드 오류

wingle/src/main/java/kr/co/wingle/common/config/SecurityConfig.java
- sever url 들어갔을 때 hello world 나올 수 있도록 수정했습니다.
resolved: #40
=> [fix] SecuriyConfig url 추가 #40

wingle/src/main/java/kr/co/wingle/common/config/RedisConfig.java, wingle/src/main/java/kr/co/wingle/common/util/RedisUtil.java
- 비밀번호 인증 추가
- 유효시간 millis로 수정
- EC2에 설치한 Redis 연결할 수 있도록 RedisConfig에 password 인증 추가했습니다
- application.yml 바꿨고 github action secret도 바꿔두었습니다
resolved: #48
=> [Breaking change] RedisConfig 수정

wingle/src/main/java/kr/co/wingle/member/AuthController.java, wingle/src/main/java/kr/co/wingle/member/MemberController.java, wingle/src/main/java/kr/co/wingle/member/MemberRepository.java, wingle/src/main/java/kr/co/wingle/member/dto/MemberResponseDto.java, wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java, wingle/src/main/java/kr/co/wingle/member/entity/Authority.java, wingle/src/main/java/kr/co/wingle/member/entity/Member.java, wingle/src/main/java/kr/co/wingle/member/entity/Permission.java, wingle/src/main/java/kr/co/wingle/member/entity/Term.java, wingle/src/main/java/kr/co/wingle/member/entity/TermMember.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/main/java/kr/co/wingle/member/service/CustomUserDetailsService.java, wingle/src/main/java/kr/co/wingle/member/service/MailService.java, wingle/src/main/java/kr/co/wingle/member/service/MemberService.java, wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java, wingle/src/test/java/kr/co/wingle/member/AuthServiceTest.java, wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
- member 패키지 안에서 파일 보기가 불편해서, service와 entity 패키지를 만들어 정리했습니다.
resolved: #54
=> [refactor] member 폴더 구조 정리

wingle/src/main/java/kr/co/wingle/common/jwt/TokenProvider.java, wingle/src/main/java/kr/co/wingle/member/AuthController.java, wingle/src/main/java/kr/co/wingle/member/dto/LoginResponseDto.java, wingle/src/main/java/kr/co/wingle/member/dto/TokenDto.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java, wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
- 로그인 응답 DTO를 따로 만들어서 관리자 여부인지 확인하는 필드와, 인증 접두사 필드를 추가했습니다.
- 토큰 DTO에도 인증 접두사 필드를 추가했습니다.
- 로그인
- 토큰 재발급
resolved: #68
=> [refactor] 토큰 응답 수정

wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/member/AuthController.java, wingle/src/main/java/kr/co/wingle/member/AuthService.java, wingle/src/main/java/kr/co/wingle/member/dto/NicknameRequestDto.java, wingle/src/main/java/kr/co/wingle/member/dto/NicknameResponseDto.java, wingle/src/main/java/kr/co/wingle/profile/Profile.java, wingle/src/main/java/kr/co/wingle/profile/ProfileRepository.java, wingle/src/main/java/kr/co/wingle/profile/ProfileService.java, wingle/src/test/java/kr/co/wingle/member/AuthServiceTest.java
- 중복된 닉네임 사용을 허용하지 않으므로 이미 사용 중인 닉네임인지 검사가 필요합니다.
- 따라서 사용자가 등록/수정하려는 닉네임이 이미 존재하는지 검사하는 API를 구현하였습니다.
- 사용 가능한 닉네임인 경우 true 로 응답합니다.
- 중복된 닉네임인 경우 Exception을 발생시키고 400 서버로 응답합니다.
resolved: #39
=> Feat/닉네임 중복 확인하기 #39

wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/member/MemberController.java, wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java, wingle/src/main/java/kr/co/wingle/member/service/MemberService.java, wingle/src/test/java/kr/co/wingle/member/MemberControllerTest.java, wingle/src/test/java/kr/co/wingle/member/service/MemberServiceTest.java
- 수락 대기 사용자 조회 API 구현 완료했습니다.
- 테스트 결과
resolved: #67
=> [feat] 수락 대기 사용자 조회 API

wingle/build.gradle, wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/community/forum/Forum.java, wingle/src/main/java/kr/co/wingle/community/forum/ForumController.java, wingle/src/main/java/kr/co/wingle/community/forum/ForumMapper.java, wingle/src/main/java/kr/co/wingle/community/forum/ForumRepository.java, wingle/src/main/java/kr/co/wingle/community/forum/ForumResponseDto.java, wingle/src/main/java/kr/co/wingle/community/forum/ForumService.java, wingle/src/main/java/kr/co/wingle/community/writing/Writing.java, wingle/src/main/java/kr/co/wingle/community/writing/WritingDto.java, wingle/src/main/java/kr/co/wingle/community/writing/WritingRepository.java, wingle/src/main/java/kr/co/wingle/community/writing/WritingService.java, wingle/src/main/java/kr/co/wingle/member/MemberService.java, wingle/src/test/java/kr/co/wingle/community/forum/ForumControllerTest.java, wingle/src/test/java/kr/co/wingle/community/forum/ForumServiceTest.java, wingle/src/test/resources/data/insert-member.sql
- 게시판 조회 API 입니다.
resolved: #20
=> [feat] 게시판 조회 #20

wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/profile/ProfileController.java, wingle/src/main/java/kr/co/wingle/profile/ProfileService.java, wingle/src/main/java/kr/co/wingle/profile/dto/ProfileGetResponseDto.java, wingle/src/main/java/kr/co/wingle/profile/dto/ProfileRegistrationResponseDto.java, wingle/src/main/java/kr/co/wingle/profile/dto/ProfileResponseDto.java
Success Code '프로필 조회 성공' , '프로필 등록여부 조회 성공' 추가하였습니다.
- 프로필 조회 API
- 프로필 등록 여부 조회
resolved: #83
=> Feat/프로필 조회 api #83

wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
- 회원가입 응답 시 닉네임 반환하는 부분 수정했습니다.
resolved: #91
=> [fix] 회원가입 응답 로직 수정 #91

wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
프론트 연결 편의성을 위해 모두 허용
나중에 프론트 도메인만 허용해야함
- API 연결 위해 모든 도메인 허용
- 나중에 프론트 도메인만 설정해줘야함
=> [feat] CORS 오류 해결 #94

wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
- 프론트 오리진 추가 (localhost 및 윙글 도메인)
- 쿠키 요청 허용
- 프리 플라이트 캐싱
resolved: #94
=> Feat/cors 문제 해결 #94

wingle/src/main/java/kr/co/wingle/common/aop/LogAspect.java, wingle/src/main/java/kr/co/wingle/member/AuthController.java
- [] 문서변경이 필요한 경우, 변경하였나요?
- 로그에 로그인한 유저 이메일 정보 넣었습니다.
resolved: #100
=> [refactor] 로그 내용 수정

wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
-  3000~3010 포트 허용
resolved: #94
=> [feat] 로컬호스트 허용 포트 추가 #94

wingle/src/main/java/kr/co/wingle/community/article/ArticleController.java
- 게시글 목록 보기 경로 수정
- articles/?size={}page={} -> /articles?size={}page={}로 변경
resolved: #104
=> [fix] 게시글 목록 보기 경로 수정 #104

wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
- 관리자 페이지네이션 사이즈 조정
- 15 -> 10 으로 조정
resolved: #108
=> Feat/관리자 페이지네이션 사이즈 조정 #108

wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
- get, post, head, put, patch, delete
resolved: #94
=> [feat] CORS 허용 http 메서드 추가 #94

wingle/build.gradle, wingle/src/docs/asciidoc/community/forum/forumApi.adoc, wingle/src/docs/asciidoc/index.adoc, wingle/src/main/java/kr/co/wingle/common/config/SecurityConfig.java, wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/member/MemberController.java, wingle/src/main/java/kr/co/wingle/member/dto/RejectionRequestDto.java, wingle/src/main/java/kr/co/wingle/member/dto/RejectionResponseDto.java, wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java, wingle/src/main/java/kr/co/wingle/member/entity/Member.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/main/java/kr/co/wingle/member/service/MemberService.java, wingle/src/test/java/kr/co/wingle/community/forum/ForumControllerTest.java, wingle/src/test/java/kr/co/wingle/util/ControllerTest.java, wingle/src/test/java/kr/co/wingle/util/RestDocsConfig.java, wingle/src/test/java/kr/co/wingle/util/RestDocsTestSupport.java, wingle/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet, wingle/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet, wingle/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
- 어드민 회원가입 거절사유 저장 및 조회
resolved: #110
=> Feat/어드민 회원가입 거절사유 #110

wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
- 쪽지 없는 경우 에러 처리
- 쪽지 없으면 빈 배열 보냄
resolved: #121
=> [fix] 쪽지 없는 경우 에러 처리 #121

wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseDto.java, wingle/src/main/java/kr/co/wingle/message/service/MessageService.java
최근 쪽지가 아래로 오게 정렬
- 최근 쪽지가 아래로 오게 정렬
resolved: #123
=> [feat] 쪽지 목록 역순 정렬 #123

wingle/src/main/java/kr/co/wingle/member/MemberController.java, wingle/src/main/java/kr/co/wingle/member/MemberRepository.java, wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseWithPagesDto.java, wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
- 기존 ResponseDto를 감싸는 Dto 신규 생성
- Page 객체를 리턴받는 함수 추가
=> [faet] 사용자 대기,수락,거절 목록 조회에 페이지 추가 #125

wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentService.java
- 댓글 삭제 안되는 오류 수정 (400 잘못된 요청 파라미터)
- 기존 != 로 비교하던거 equals()로 수정 (Long 타입은 -128~127까지만 ==로 정상동작)
resolved: #126
=> [fix] Long 비교 연산자 수정

wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java
- 게시글 및 댓글 관련 api response body에 userImage 추가
resolved: #129
=> [add] 게시글 & 댓글 res에 userImage 추가

wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentService.java, wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java, wingle/src/main/java/kr/co/wingle/member/AuthController.java, wingle/src/main/java/kr/co/wingle/member/MemberController.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/main/java/kr/co/wingle/member/service/MemberService.java, wingle/src/main/java/kr/co/wingle/message/service/MessageService.java, wingle/src/main/java/kr/co/wingle/message/service/RoomService.java, wingle/src/main/java/kr/co/wingle/profile/ProfileService.java, wingle/src/main/java/kr/co/wingle/writing/WritingService.java, wingle/src/main/java/kr/co/wingle/writing/WritingUtil.java, wingle/src/test/java/kr/co/wingle/member/AuthControllerTest.java, wingle/src/test/java/kr/co/wingle/member/MemberControllerTest.java, wingle/src/test/java/kr/co/wingle/member/service/AuthServiceTest.java
- 미승인 유저 접근 비허용
resolved: #128
=> Fix/미승인 유저 접근 비허용 #128

wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
- 관리자도 컨텐츠 접근가능하게 수정
resolved: #128
=> [fix] 관리자도 컨텐츠 접근가능하게 수정 #128

wingle/build.gradle, wingle/src/main/resources/logback-spring.xml, wingle/src/main/resources/logback.xml
- `logback-awslogs-appender` 디펜던시 추가
- 유진이가 만든 `logback-spring.xml`을 일부 참고
- 테스트를 위해, prod 환경의 error 로그만 작성
- 더이상 파일 시스템에 로그가 쌓이지 않도록 유진이 코드를 주석처리하였습니다
resolved: #136
=> [refactor]  CloudWatch로의 로그 전송 환경 세팅 #136

wingle/src/main/java/kr/co/wingle/profile/ProfileController.java, wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
API - http://localhost:8080/api/v1/profile/{id}
resolved: #139
=> [feat] 타인-프로필-조회 #139

wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java, wingle/src/main/java/kr/co/wingle/common/filter/ReadableRequestBodyWrapper.java, wingle/src/main/java/kr/co/wingle/common/filter/ReadableResponseBodyWrapper.java, wingle/src/main/resources/logback-spring.xml, wingle/src/main/resources/logback.xml
- CloudWatch 로그 형식 변경
- 시간대 중복 기록, 스레드 기록 삭제
- request, response 로그 추가
resolved: #136
=> Refactor/cloudWatch request, response 세팅 #136

wingle/src/main/java/kr/co/wingle/common/aop/LogAspect.java, wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java, wingle/src/main/java/kr/co/wingle/common/filter/ReadableRequestBodyWrapper.java, wingle/src/main/java/kr/co/wingle/common/filter/ReadableResponseBodyWrapper.java, wingle/src/main/resources/logback-spring.xml
- 필터를 통해 Req, Res 로깅을 추가하였습니다
- method 단위 로깅이 너무 많이 기록되어, debug 레벨로 수정하였습니다
- cloudwatch 에서 한눈에 로그를 보기 어려워 로그 길이를 조금 축소하였습니다
=> Refactor/Req, Res 로깅 추가 #136

wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java
- form-data의 경우 multipart 형식이기 때문에 HttpRequestWrapper에서 처리하면 컨트롤러에서 null로 받게 되는 이슈
- form-data를 처리하는 분기를 추가하였습니다
resolved: #152
=> Fix/ form-data request를 처리할 수 있도록 분기 추가

wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java
request.getContentType().startsWith()에서 request.getContentType()에 null값이 들어가서 null 방지 추가
-  request.getContentType().startsWith()에서 request.getContentType()에 null값이 들어가서 null 방지 추가
resolved: #156
=> [fix] null 방지 코드 추가 #156

wingle/src/main/java/kr/co/wingle/common/filter/ApiLoggingFilter.java
- cloud watch 로깅에서 hello world가 빈번히 찍히는 이슈
- hello api는 로깅에서 제외할 수 있도록 수정
resolved: #154
=> [refactor] 로깅에서 hello api 제외

wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentResponseDto.java
- 커뮤니티(댓글, 게시글)부분 멤버아이디 암호화했습니다.
- 암호화된 멤버아이디가 String이라서 Response가 Long->String으로 수정되었습니다.
- AES256Util encrypt, decrypt 함수에서 각각 CustonException 날리는 게 좋을 것 같아서 수정했으니 확인부탁드립니다.
resolved: #158
=> Fix/커뮤니티 멤버아이디 암호화 #158

wingle/src/main/java/kr/co/wingle/community/article/ArticleRequestDto.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java, wingle/src/main/java/kr/co/wingle/writing/Writing.java
게시글, 댓글 최대글자수 수정했습니다.
- writing entity content column TEXT로 수정
- 게시글: 최대 1000자
- 댓글: 최대 500자
resolved: #166
=> [fix] 게시글, 댓글 최대글자수 수정

wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentService.java
커뮤니티 리스트 조회 정렬 수정했습니다.
- 게시글 : createdTime Descending
- 댓글: createdTime Ascending
resolved: #160
=> Fix/커뮤니티 정렬 수정 #160

wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
- 인증코드 전송 시 이메일 중복처리 추가했습니다. (프론트 요청)
resolved: #169
=> [add] 인증코드 전송 시 이메일 중복처리 추가

wingle/src/main/java/kr/co/wingle/member/service/MailService.java
- 에러 확인을 위해 프린트문 추가했습니다..
- 고치고 지우겠습니다..
=> [add] 에러 확인을 위한 프린트문 추가

wingle/src/main/java/kr/co/wingle/member/service/MailService.java
=> [del] 프린트문 삭제

wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
- 어드민 페이지 cors 해결
resolved: #176
=> feat: allowedOrigins 에 admin 페이지 추가 #176

wingle/src/main/java/kr/co/wingle/common/config/WebMvcConfig.java
=> allowedOrigins에 web 페이지 추가 # 178

wingle/src/main/java/kr/co/wingle/common/util/RedisUtil.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
=> [add] 에러 고치기 위한 System.out 추가

wingle/src/main/java/kr/co/wingle/common/util/RedisUtil.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
Reverts Wingle-SMWU/Wingle-Backend#182
=> Revert "[add] 에러 고치기 위한 System.out 추가"

wingle/src/main/java/kr/co/wingle/member/mailVo/ApplyMail.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/main/java/kr/co/wingle/member/service/MailService.java, wingle/src/main/resources/templates/acceptance.html, wingle/src/main/resources/templates/apply.html, wingle/src/main/resources/templates/rejection.html
- 회원가입 완료 이메일 발송
- 가입 수락/ 거절 이메일 문구 수정
resolved: #184
=> Feat/회원가입 완료 이메일 #184

wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseWithRecipentDto.java, wingle/src/main/java/kr/co/wingle/message/dto/RoomMemberDto.java, wingle/src/main/java/kr/co/wingle/message/service/MessageService.java, wingle/src/main/java/kr/co/wingle/message/service/RoomService.java
- 쪽지 내역 조회에 UserId 추가
- 여기에 추가되는 UserId는 암호화되지 않은 버전으로 추가하였습니다(추후 암호화 브랜치에 별도 작업 후 머지)
resolved: #195
=> [feat] 쪽지 내역 조회에 UserID 추가 # 195

wingle/src/main/java/kr/co/wingle/member/mailVo/CodeMail.java
- 인증코드 유효시간 3분에서  5분으로 수정 (기획 1차 QA)
resolved: #197
=> [fix] 인증코드 유효시간 3분에서  5분으로 수정

wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscape.java, wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscapeValidator.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleRequestDto.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java
게시글, 댓글 최대글자수 변경 및 글자수 validator 수정 (1차 QA)
- 게시글 최대 3000자로 수정
- 댓글 최대 1000자로 수정
- validator 커스텀해서 수정함
배포하고 확인해봐야 할 부분 있음
resolved: #194
=> [fix] 게시글, 댓글 최대글자수 변경 및 글자수 validator 수정

wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscapeValidator.java
- validator 수정 (테스트중)
resolved: #194
=> [fix] validator 수정

wingle/src/main/java/kr/co/wingle/common/validator/LengthWithLiteralEscapeValidator.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleRequestDto.java
- validator 수정 및 게시글 최대 3000자로 변경
//s 로 하면 whitespace replace가 안됨.. 왜그런지는 모르겠음
resolved: #194
=> [fix] validator 수정 및 게시글 최대 3000자로 변경

wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
- 1차 QA 대응
- 가입 대기중, 거절된 회원은 로그인 불가
- 가입 승인된 유저만 로그인 가능
resolved: #188
=> [fix] 승인된 유저만 로그인 허용 #188

wingle/src/main/java/kr/co/wingle/profile/dto/ProfileRequestDto.java
- nickname 형식 유효검사 수정 (한글/영문/숫자 2-10자)
resolved: #203
=> [fix] nickname 형식 유효검사 수정 (한글/영문/숫자 2-10자)

wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
- 사용가능언어 중복값 제거 후 저장 (Set으로 감싸고 저장)
resolved: #204
=> [fix] 사용가능언어 중복값 제거 후 저장

wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/member/TermMemberRepository.java, wingle/src/main/java/kr/co/wingle/member/entity/Member.java, wingle/src/main/java/kr/co/wingle/member/entity/TermMember.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/main/java/kr/co/wingle/profile/ProfileService.java, wingle/src/main/java/kr/co/wingle/profile/entity/Profile.java, wingle/src/main/java/kr/co/wingle/profile/util/ProfileUtil.java
- 1차 QA 대응
- 가입 거절된 회원 재가입 허용
resolved: #187
=> Fix/가입 거절된 회원 재가입 허용 #187

wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
- 중복 이메일 res 수정 (회원가입이 불가능한 이메일입니다 -> 이미 가입된 유저입니다)
- 이메일 전송 횟수 초과된 부분 http status 200 -> 400 수정 
-> CustomException http status 200 -> 400으로 수정 **프론트 확인 필요**
resolved: #208
=> Fix/중복 이메일 res 수정 #208

wingle/src/main/java/kr/co/wingle/common/validator/LengthWithoutCR.java, wingle/src/main/java/kr/co/wingle/common/validator/LengthWithoutCRValidator.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleRequestDto.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java
content length check validator 수정
- 줄바꿈이 CRLF로 들어가서 길이가 2개로 count되는 문제 -> CR 제외하고 length check하는걸로 수정
resolved: #194
=> [fix] content length check validator 수정

wingle/src/main/java/kr/co/wingle/profile/dto/IntroductionRequestDto.java
- 자기소개 request 글자수 제한 400자로 수정
resolved: #215
=> [fix] 자기소개 request 글자수 제한 수정

wingle/src/main/java/kr/co/wingle/profile/dto/IntroductionRequestDto.java
- 자기소개 글자수 제한 메시지 수정
resolved: #215
=> [fix] 자기소개 글자수 제한 메시지 수정

wingle/build.gradle, wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentRequestDto.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentResponseDto.java, wingle/src/main/java/kr/co/wingle/member/MemberController.java, wingle/src/main/java/kr/co/wingle/member/dto/AcceptanceRequestDto.java, wingle/src/main/java/kr/co/wingle/member/dto/MemoRequestDto.java, wingle/src/main/java/kr/co/wingle/member/dto/PermissionResponseDto.java, wingle/src/main/java/kr/co/wingle/member/dto/RejectionRequestDto.java, wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseDto.java, wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/main/java/kr/co/wingle/member/service/MemberService.java, wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseWithRecipentDto.java, wingle/src/main/java/kr/co/wingle/message/dto/RoomRequestDto.java, wingle/src/main/java/kr/co/wingle/message/mapper/MessageMapper.java, wingle/src/main/java/kr/co/wingle/message/service/MessageService.java, wingle/src/main/java/kr/co/wingle/message/service/RoomService.java, wingle/src/main/java/kr/co/wingle/profile/ProfileController.java, wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
**File changed가 상당히 많은데, Revert 코드까지 changed로 잡혀서 그래요.
`6c5eb96` 커밋으로 들어가서 확인해주심 됩니다**
- 쪽지, admin 쪽 userId 암호화
resolved: #219
=> [feat] 누락된 userId 암호화 반영

wingle/src/main/java/kr/co/wingle/community/forum/ForumService.java
- 공지게시판 작성자 이름 변경
resolved: #221
=> [fix] 공지게시판 작성자 이름 변경

wingle/src/main/java/kr/co/wingle/affliation/controller/AffliationController.java, wingle/src/main/java/kr/co/wingle/affliation/dto/SchoolResponseDto.java, wingle/src/main/java/kr/co/wingle/affliation/entity/School.java, wingle/src/main/java/kr/co/wingle/affliation/repository/SchoolRepository.java, wingle/src/main/java/kr/co/wingle/affliation/service/SchoolService.java, wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java, wingle/src/main/java/kr/co/wingle/member/entity/Member.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java, wingle/src/test/java/kr/co/wingle/member/service/MemberServiceTest.java
- 회원가입 학교 학과 학번 추가
- 학교 리스트 조회 API 추가
resolved: #218
=> Feat/회원가입 학교 학과 학번 추가 #218

wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/common/util/S3Util.java, wingle/src/main/java/kr/co/wingle/member/AuthController.java, wingle/src/main/java/kr/co/wingle/member/dto/IdCardImageReqeustDto.java, wingle/src/main/java/kr/co/wingle/member/dto/IdCardImageResponseDto.java, wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/test/java/kr/co/wingle/member/MemberTemplate.java
- 학생증 업로드 API 생성
- 회원 가입 시 이미지를 직접 보내지 않고 이미지 url 보냄
resolved: #213
=> Feat/학생증 업로드 #213

wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleResponseDto.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentResponseDto.java, wingle/src/main/java/kr/co/wingle/community/forum/ForumService.java, wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java, wingle/src/main/java/kr/co/wingle/community/util/ProcessedPersonalInformation.java
게시글, 댓글 response에 사용자 대학명 추가
- 자유, 공지 게시판 -> "" return
- 교류 게시판 -> 실제 학교 이름 return
커뮤니티 부분 건드리는 김에 AES256Util static 함수 쓰는걸로 변경해줬습니다..!
resolved: #226
=> Add/커뮤니티 res 대학명 추가 #226

wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
=> [fix] 커뮤니티 response 사용자 대학명 오류 수정

wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
=> [feat] admin 사용자 상세조회에 학교, 학과, 학번 추가

wingle/src/main/java/kr/co/wingle/message/dto/MessageResponseWithRecipentDto.java, wingle/src/main/java/kr/co/wingle/message/dto/RoomMemberDto.java, wingle/src/main/java/kr/co/wingle/message/service/MessageService.java, wingle/src/main/java/kr/co/wingle/message/service/RoomService.java, wingle/src/main/java/kr/co/wingle/profile/ProfileService.java, wingle/src/main/java/kr/co/wingle/profile/dto/ProfileGetResponseDto.java
=> [feature] 프로필, 쪽지 내역 조회 시 학교명 추가 #231

wingle/src/main/java/kr/co/wingle/member/MemberController.java, wingle/src/main/java/kr/co/wingle/member/MemberRepository.java, wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseWithPagesDto.java, wingle/src/main/java/kr/co/wingle/member/service/MemberService.java
=> [feat] admin 리스트 조회 시 전체 유저수 조회

wingle/src/main/java/kr/co/wingle/member/dto/WaitingUserResponseDto.java
=> [feat] admin 상세 조회시 updateTime, permission 추가 반환

wingle/src/main/java/kr/co/wingle/member/dto/SignupResponseDto.java, wingle/src/main/resources/templates/acceptance.html, wingle/src/main/resources/templates/apply.html, wingle/src/main/resources/templates/code.html, wingle/src/main/resources/templates/rejection.html
- 이메일 모바일 대응
- 회원가입 완료 시 user id 암호화 fix
resolved: #237
=> Feat/이메일 반응형 #237

wingle/src/main/java/kr/co/wingle/community/forum/ForumService.java
- 익명게시판 한국윙그리 외국윙그리 구분값 수정
- 구분 국적값 code -> enNation으로 변경된 사항 반영
resolved: #239
=> [fix] 익명게시판 외국윙그리 한국윙그리 구분 국적값 변경 (code->enNation)

wingle/src/main/java/kr/co/wingle/member/dto/SignupListResponseDto.java
QA 사항 반영
- 리스트 조회 시 상태, 상태에 따른 일자, 학교이름 정보 추가
resolved: #241
=> [add] 리스트 조회 시 상태, 상태에 따른 일자, 학교이름 정보 추가

wingle/src/main/java/kr/co/wingle/affliation/repository/SchoolRepository.java, wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/member/dto/SignupRequestDto.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java
- 회원가입 시 학교id 대신 학교 코드 받아서 회원가입 진행
resolved: #243
=> [feat] 회원가입 시 학교 코드 받기 추가 #243

wingle/src/main/java/kr/co/wingle/profile/ProfileService.java
- 사용언어 리스트 순서 오류 (HashSet으로 감싸면서 리스트 순서가 사라짐 -> linkedHashSet 사용)
resolved: #245
=> [fix] 사용언어 리스트 순서 오류

wingle/src/main/java/kr/co/wingle/profile/ProfileService.java, wingle/src/main/java/kr/co/wingle/profile/dto/ProfileViewResponseDto.java
- 프로필 상세조회 response에 학교명 추가
resolved: #247
=> [add] 프로필 상세조회 response에 학교명 추가

wingle/src/main/java/kr/co/wingle/member/mailVo/AcceptanceMail.java, wingle/src/main/java/kr/co/wingle/member/mailVo/ApplyMail.java, wingle/src/main/java/kr/co/wingle/member/mailVo/Mail.java, wingle/src/main/java/kr/co/wingle/member/mailVo/RejectionMail.java, wingle/src/main/java/kr/co/wingle/member/service/AuthService.java, wingle/src/main/java/kr/co/wingle/profile/entity/Nation.java, wingle/src/main/java/kr/co/wingle/profile/util/ProfileUtil.java, wingle/src/main/resources/templates/acceptanceEn.html, wingle/src/main/resources/templates/applyEn.html, wingle/src/main/resources/templates/rejectionEn.html
- 외국인에게 영문으로 이메일 전송
resolved: #249
=> Feat/영문 이메일 #249

.github/workflows/deploy.yml, wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java, wingle/src/main/java/kr/co/wingle/common/util/S3Util.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleImage.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleImageRepository.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleMapper.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java, wingle/src/main/java/kr/co/wingle/community/comment/CommentMapper.java
- 커뮤니티 게시글 사진 업로드 기능 추가
resolved: #256
=> Feat/커뮤니티 게시글 사진 업로드 #256

wingle/src/main/java/kr/co/wingle/common/constants/ErrorCode.java, wingle/src/main/java/kr/co/wingle/message/controller/MessageController.java, wingle/src/main/java/kr/co/wingle/message/dto/RoomResponseDto.java, wingle/src/main/java/kr/co/wingle/message/dto/UnreadMessageCountResponseDto.java, wingle/src/main/java/kr/co/wingle/message/entity/RoomMember.java, wingle/src/main/java/kr/co/wingle/message/service/MessageService.java, wingle/src/main/java/kr/co/wingle/message/service/RoomService.java
- 안 읽은 쪽지 관련 API 개발
resolved: #264
=> Feat/안 읽은 쪽지 개수 추가 #264

wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
- 탈퇴한 유저의 자유게시판 글 조회 시 닉네임 (알수없음)으로 수정
=> [fix] 탈퇴한 유저의 자유게시판 글 조회 시 닉네임 (알수없음)으로 수정

wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java
- 복호화 시 Hex decode 하도록 수정
resolved: #268
=> [fix] 복호화 시 Hex decode 하도록 수정

.github/workflows/deploy-main.yml, wingle/src/main/java/kr/co/wingle/common/util/AES256Util.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleService.java, wingle/src/main/java/kr/co/wingle/community/util/CommunityUtil.java
- 게시글 작성 및 수정에서 이미지 없을 때 오류 수정
- 탈퇴한 유저 자유게시판 글(게시글, 댓글) 조회 시 닉네임도 "(알수없음)"으로 수정
- 복호화 오류 수정
resolved: #
=> [merge] 오류 수정사항 test 브랜치에 머지

wingle/src/main/java/kr/co/wingle/common/constants/SuccessCode.java, wingle/src/main/java/kr/co/wingle/community/article/ArticleController.java, wingle/src/main/java/kr/co/wingle/member/AuthController.java
수정사항 test 브랜치에 머지
- 회원탈퇴 response message 수정
- 게시글 수정 response message 수정
=> [merge] 수정사항 test 브랜치에 머지

wingle/src/main/java/kr/co/wingle/community/article/ArticleEditRequestDto.java
- 게시글 수정 req dto notnull validator 추가
=> [add] 게시글 수정 req dto notnull validator 추가
